name: RECALL
version: ${project.version}
main: cc.eumc.recall.RECALL
api-version: 1.13
authors: [ElaBosak233]
description: Call your friends together quickly !
website: https://elabosak233.github.io

commands:
  rc:
    description: Spend money to enable [[RECALL]]
    usage: /rc
    permission: RECALL.rc
    permission-message: You don't have permission to use [[RECALL]]
  rccancel:
    description: Cancel your [[RECALL]]
    usage: /rccancel
    permission: RECALL.rccancel
    permission-message: You don't have permission to use /rccancel
  rcaccept:
    description: Accept others [[RECALL]]
    usage: /rcaccept [Playername]
    permission: RECALL.rcaccept
    permission-message: You don't have permission to use /rcaccept
  rchelp:
    description: Read [[RECALL]] help
    usage: /rchelp
    permission: RECALL.rchelp
    permission-message: You don't have permission to use /rchelp
